
spring:
  application:
    name: recruitProject
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruitsystem
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ali:
  OSS:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: recruitsystem


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
